#!/bin/sh

case $BLOCK_BUTTON in
    1) notify-send "hi" ;;
    3) notify-send "Dmenu-Wifi Module" "Right click for selecting Wifis\nMiddle Click for this help msg\nShift click for editing source";;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac


ssid=$( nmcli device wifi list --rescan yes | rg -o  ":..\s(.*?)\bIn" | awk '{ $1=$NF="";print}' | sort -u |dmenu -p "SSID :")

if [ -n "$ssid" ];
then
    out=$(nmcli device wifi connect "$ssid")
    # Notify user of the connection status
    if [[ $? -eq 0 ]]; then
        notify-send "WIFI Connect" "Connected to $ssid"
    else
        notify-send "WIFI Connect" "Failed to connect to $ssid: $out"
    fi
    pkill -RTMIN+11 dwmblocks;
fi

