#!/bin/bash

mount=$(echo -e "Mount\nUmount" | dmenu -p "Mount or Umount ? :")
echo $mount
if [ $mount = "Mount" ];
then
	#part=$(echo "$(ls -1 /dev/sd[a-z][0-9] | cut -d"/" -f3)"| dmenu -p "CHOSE PARTITION :")
	part="sdc2"
	pass=$(dmenu -P -p "Password :")

	#echo $part
	#echo $pass

	echo $pass | sudo cryptsetup open /dev/$part m_part - 
	sudo mount /dev/mapper/m_part /mnt

elif [ $mount = "Umount" ]
then
	sudo umount /mnt
	sudo cryptsetup close /dev/mapper/m_part

fi



