#!/bin/bash
set -x
dirs=("$HOME/Downloads" "$HOME/Downloads/enter/courses" "$HOME/Downloads/media"
    "$HOME/scripts" "$HOME/.config" "$HOME/wm" "$HOME/wm/dwm" "$HOME/wm/st" "$HOME/.local/share")

for dir in "${dirs[@]}";do
    content+="$(tree -f "$dir" -L 1 -a -i -n)";
done

file=$(echo "$content" | dmenu -l 20  -p "File :")
[ -z "$file" ] && exit 0;
file_type=$(file -b "$file")

case "$file_type" in 
    *"PDF"*)
        lnch zathura "$file";
        ;;
    *"MP4"* | *"video"* | *"matroska"*)
        lnch mpv "$file";
        ;;
    *"shell"*)
        lnch st -e nvim "$file";
        ;;
    *"directory"*)
        choice=$(printf "Play with mpv\nCopy Path\nOpen with nvim\nOpen terminal here" | dmenu -p "Choose >");
        case "$choice" in
            "Play with mpv")
                lnch mpv "$file";
                ;;
            "Copy Path")
                xclip "$file";
                ;;
            "Open with nvim")
                st -e nvim "$file";
                ;;
            "Open terminal here")
                lnch st -e cd "$file";
                ;;
            *)
                exit 0;
                ;;
        esac;;
    *)
        echo cached;
        lnch xdg-open "$file"
        ;;
esac




