#!/bin/sh

var=$(echo -e "Power-off\nReboot\nSuspend\nHibernate\nHybrid-sleep\nkill-dwm" | dmenu)
#echo $var
if [ "$var" == "Power-off" ]; then
    pkexec shutdown now
elif [ "$var" == "Reboot" ]; then
    pkexec reboot
elif [ "$var" == "kill-dwm" ]; then
    killall dwmblocks & killall dunst & killall dwm
elif [ "$var" == "Suspend" ]; then
    i3lock-fancy & pkexec systemctl suspend
elif [ "$var" == "Hibernate" ]; then
    i3lock-fancy & pkexec systemctl hibernate
elif [ "$var" == "Hybrid-sleep" ]; then
    i3lock-fancy & pkexec systemctl hybrid-sleep
fi

