#!/bin/sh

var=$(echo -e "Power-off\nReboot\nSuspend\nHibernate\nHybrid-sleep\nkill-dwm" | dmenu)

if [ "$var" == "Power-off" ]; then
    pkexec shutdown now
elif [ "$var" == "Reboot" ]; then
    pkexec reboot
elif [ "$var" == "kill-dwm" ]; then
    killall dwmblocks & killall dunst & killall dwm
elif [ "$var" == "Suspend" ]; then
    sudo -A systemctl suspend && i3lock
elif [ "$var" == "Hibernate" ]; then
    sudo -A systemctl hibernate && i3lock
elif [ "$var" == "Hybrid-sleep" ]; then
    sudo -A systemctl hybrid-sleep && i3lock
fi

