#!/bin/sh

tmp_file="$HOME/.local/share/git_tree_output.txt"
ignore="nvim|paru|anaconda|oh-my-zsh|Trash|plugins|Code|icons|extensions|repositories|cargo|site-packages|node_modules"

if find $tmp_file -mtime -5 >/dev/null 2>&1; then
    echo "Using cached file"
else
    mapfile -t output_array < <(locate -r "\.git$" | grep -Evw "$ignore")
    all_ls_output=""
    for element in "${output_array[@]}"; do
        element_without_git=$(echo "$element" | sed 's/\.git$//')
        all_ls_output+="$(tree -ifa -I ".git" -I "site-packages" -I "node_modules" "$element_without_git")"
    done

    echo "$all_ls_output" > "$tmp_file"
    echo "Updated cached file"
fi

fzf --preview="bat -f {}" --bind="enter:execute(nvim {})" --expect=ctrl-c < "$tmp_file"



