#! /bin/sh

shopt -s nocasematch
if [ ! -z "$1" ];then
        a=$1
else
        a=$(echo -e "Dwmblocks\nSXHKD\nDWM\nDunst\nTransmission\nI2P Router" | dmenu )
fi

case "$a" in 
        "Dwmblocks")
                killall dwmblocks;
                dwmblocks &
                ;;

        "Dunst")
                killall dunst;
                dunst &
                ;;

        "DWM")
                pkill -HUP dwm >> /tmp/dwm_log
                ;;

        "SXHKD")
                out=$(killall sxhkd)
                sxhkd &
                ;;

        "Transmission")
                if [ ! -z "$(ps -aux | grep transmission | grep daemon)" ]
                then
                        out=$(systemctl restart transmission)
                else
                        out=$(systemctl start transmission)
                fi
                ;;

        "I2P Router")
                if [ -z "$(i2prouter status | grep not running)" ]
                then
                        out=$(i2prouter start)
                else
                        out=$(i2prouter stop) 
                fi
                ;;
esac

[ ! -z "$a" ] && [ ! -z "$out" ] && dunstify "$a" "$out"


