#! /bin/sh

shopt -s nocasematch
[ ! -z "$1" ] && a=$1 || a=$(echo -e "Dwmblocks\nSXHKD\nDWM\nDunst\nTransmission\nI2P Router" | dmenu -p "Reload >")

case "$a" in 
    "Dwmblocks")
        if [ ! -z "$(pidof dwmblocks)" ]
        then
            a=$(echo -e "Restart\nKill" | dmenu -p "Dwmblocks is already running. What to do? >");
            [ -z $a ] && exit;
            [ $a == "Restart" ] && (killall dwmblocks; dwmblocks &) ||  (killall dwmblocks)

        else
            a=$(echo -e "Start"| dmenu -p "Dwmblocks is not running. What to do? >")
            [ -z $a ] && exit || (dwmblocks &)
        fi
        ;;

    "Dunst")
        if [ ! -z "$(pidof dunst)" ]
        then
            a=$(echo -e "Restart\nKill" | dmenu -p "Dunst is already running. What to do? >")
            [ -z $a ] && exit;
            [ $a == "Restart" ] && (killall dunst;dunst &) || (killall dunst)
        else
            a=$(echo -e "Start"| dmenu -p "Dunst is not running. What to do? >")
            [ -z $a ] && exit || (dunst &)
        fi
        ;;

    "DWM")
        pkill -HUP dwm >> /tmp/dwm_log
        ;;

    "SXHKD")
        if [ ! -z "$(pidof sxhkd)" ]
        then
            a=$(echo -e "Restart\nKill" | dmenu -p "Dunst is already running. What to do? >")
            [ -z $a ] && exit;
            if [ $a == "Restart" ] && (killall -SIGUSR1 sxhkd) || (killall dunst)
        else
            a=$(echo -e "Start"| dmenu -p "Dunst is not running. What to do? >")
            [ -z $a ] && exit || (sxhkd &)
        fi
        ;;

    "Transmission")
        if [ ! -z "$(pidof transmission-daemon)" ]
        then
            a=$(echo -e "Restart\nStop")
            [ -z $a ] && exit;
            [ $a == "Restart" ] && (out=$(systemctl restart transmission)) || (out=$(systemctl stop transmission))
        else
            a=$(echo -e "Start"| dmenu -p "Transmission Daemon not running. What to do? >")
            [ -z $a ] && exit || (out=$(systemctl start transmission))
        fi
        ;;

    "I2P Router")
        if [ -z "$(i2prouter status | grep not running)" ]
        then
            a=$(echo -e "Start" | dmenu -p "I2P is not running. What to do? >")
            [ -z $a ] && exit;
            [ $a == "Start" ] && ( out=$(i2prouter start))
        else
            a=$(echo -e "Stop" | dmenu -p "I2P is running. What to do? >")
            [ -z $a ] && exit || (i2prouter start)
        fi
        ;;
esac

[ ! -z "$a" ] && [ ! -z "$out" ] && dunstify "$a" "$out"
