#! /bin/sh

shopt -s nocasematch
[ -n "$1" ] && a=$1 || a=$(printf "Dwmblocks\nSXHKD\nDWM\nDunst\nTransmission\nI2P Router" | dmenu -p "Reload >")

#set -xv

case "$a" in 
    "Dwmblocks")
        if [ -n "$(pidof dwmblocks)" ]
        then
            a=$(printf "Restart\nKill" | dmenu -p "Dwmblocks is already running. What to do? >");
            [ -z "$a" ] && exit;
            [ "$a" = "Restart" ] && (killall dwmblocks;dwmblocks & disown;return 0 ) || (killall dwmblocks)

        else
            a=$(printf "Start"| dmenu -p "Dwmblocks is not running. What to do? >")
            [ -z "$a" ] && exit || (dwmblocks &)
        fi
        ;;

    "Dunst")
        if [ -n "$(pidof dunst)" ]
        then
            a=$(printf "Restart\nKill" | dmenu -p "Dunst is already running. What to do? >")
            [ -z "$a" ] && exit;
            [ "$a" = "Restart" ] && (killall dunst;dunst & disown;return 0 ) || (killall dunst)
        else
            a=$(printf "Start"| dmenu -p "Dunst is not running. What to do? >")
            [ -z "$a" ] && exit || (dunst &)
        fi
        ;;

    "DWM")
        pkill -HUP dwm >> /tmp/dwm_log
        ;;

    "SXHKD")
        if [ -n "$(pidof sxhkd)" ]
        then
            a=$(printf "Restart\nKill" | dmenu -p "Dunst is already running. What to do? >")
            [ -z "$a" ] && exit;
            [ "$a" = "Restart" ] && (killall -SIGUSR1 sxhkd;return 0) || (killall dunst)
        else
            a=$(printf "Start"| dmenu -p "Dunst is not running. What to do? >")
            [ -z "$a" ] && exit || (sxhkd &)
        fi
        ;;

    "Transmission")
        if [ -n "$(pidof transmission-daemon)" ]
        then
            a=$(printf "Restart\nStop")
            [ -z "$a" ] && exit;
            [ "$a" = "Restart" ] && systemctl restart transmission || systemctl stop transmission
        else
            a=$(printf "Start"| dmenu -p "Transmission Daemon not running. What to do? >")
            [ -z "$a" ] && exit || systemctl start transmission
        fi
        ;;

    "I2P Router")
        if i2prouter status | grep -q 'not running' 
        then
            a=$(printf "Start" | dmenu -p "I2P is not running. What to do? >")
            [ -z "$a" ] && exit;
            [ "$a" = "Start" ] && out=$(i2prouter start)
        else
            a=$(printf "Stop" | dmenu -p "I2P is running. What to do? >")
            [ -z "$a" ] && exit || out=$(i2prouter stop)
        fi
        ;;
esac

[ -n "$a" ] && [ -n  "$out" ] && dunstify "$a" "$out"
