#!/bin/bash

mkdir ~/wm
cd wm || exit
git clone https://github.com/AnantStrange/dwm
git clone https://github.com/AnantStrange/dwmblocks
git clone https://github.com/AnantStrange/st
git clone https://github.com/AnantStrange/dmenu


git clone https://github.com/AnantStrange/dotfiles
git clone https://github.com/AnantStrange/statusbar_scripts
git clone https://github.com/AnantStrange/scripts
git clone https://github.com/AnantStrange/nvim
git clone --depth 1 https://github.com/AnantStrange/Wallpapers.git & 

sudo pacman -Syy
sudo pacman -S --needed - < scripts/dependency

mv scripts ~ 

cd dotfiles || exit
cp .xinitrc ~
cp .zshrc ~
cp .zprofile ~
cp .alias ~
mkdir -p ~/.config/sxhkd
mkdir -p ~/.config/picom
cp sxhkdrc ~/.config/sxhkd/
cp picom.conf ~/.config/picom

sudo pacman -S --needed - < dependency
cd ~/wm || exit

cd dwm || exit
sudo make install > make_install.result 2>&1
cd ~/wm || exit

cd dwmblocks || exit
sudo make install > make_install.result 2>&1
cd ~/wm || exit

cd st || exit
sudo make install > make_install.result 2>&1
cd ~/wm || exit

cd dmenu || exit
sudo make install > make_install.result 2>&1
cd ~/wm || exit

fg
mv Wallpaper ~

mv nvim ~/.config/


