#!/bin/sh

# Check if the UTC time is provided as an argument
if [ -z "$1" ]; then
    printf "Usage: utctime <UTC_TIME_HH:MM>"
    exit 1
fi

# Extract the hours and minutes from the provided UTC time
utc_time="$1:00 UTC"

# Convert UTC time to the local timezone
local_time=$(date -d "$utc_time" +"%H:%M %Z")

echo "UTC Time: $utc_time"
echo "Local Time: $local_time"

