#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)" ;;
	2) setsid -f "$TERMINAL" -e htop ;;
	3) notify-send "🖥 CPU module " "\- Shows CPU temperature.
- Click to show intensive processes.
- Middle click to open htop." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac


if ! command -v sensors &> /dev/null; then
    echo -e "\e[1;31msensors is not installed.\e[0m To install on:"
    echo -e "  - \e[1;34mArch Linux (pacman):\e[0m sudo pacman -S sensores"

    notify-send -u critical -a "cpu/script" -t 4000 "Error: sensors is not installed" "Please install appropriate utility"

    exit 1
fi



sensors | awk '/Core 0/ {print "🌡" $3}'
